version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    restart: always
    env_file: ./.env
    ports:
      - "3000:3000" 
    depends_on:
      - auth-service
      - data-service
      - websocket-service

  auth-service:
    build: ./auth-service
    restart: always
    env_file: ./.env


  data-service:
    build: ./data-service
    restart: always
    env_file: ./.env

  worker-service:
    build: ./worker-service
    restart: always
    env_file: ./.env

  scheduler-service:
    build: ./scheduler-service
    restart: always
    env_file: ./.env

  websocket-service:
    build: ./websocket-service
    restart: always
    env_file: ./.env

