services:
  redis:
      image: redis:alpine
      restart: always
      ports:
        - "6379:6379" 
      volumes:
        - C:/D_Drive/WEB/redis-data:/data
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  api-gateway:
    build: ./api-gateway
    restart: always
    env_file: ./.env
    ports:
      - "3000:3000"  # comment this if using load-tester only
    depends_on:
      - auth-service
      - data-service
      - websocket-service
      - redis

  auth-service:
    build: ./auth-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/v1/users/health"]
      interval: 10s
      timeout: 5s
      retries: 3


  data-service:
    build: ./data-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/api/v1/data/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  graphql-service:
    build: ./graphql-service
    restart: always
    env_file: ./.env
    depends_on:
      - api-gateway
      - auth-service
      - data-service
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker-service:
    build: ./worker-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis

  scheduler-service:
    build: ./scheduler-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis

  websocket-service:
    build: ./websocket-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/api/v1/websocket/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  load-tester:
    image: yamaszone/hey
    depends_on:
      - api-gateway
      - auth-service
      - data-service
      - websocket-service
      - worker-service
      - scheduler-service
      - redis

