services:
  redis:
      image: redis:alpine
      restart: always
      ports:
        - "6379:6379" 
      volumes:
        - ${VOLUME_PATH}/redis-data:/data
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${VOLUME_PATH}/mongo-data:/data/db
    command: ["--quiet"]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH_ENABLED: ${ME_CONFIG_BASICAUTH_ENABLED}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongo

  api-gateway:
    build: ./api-gateway
    restart: always
    env_file: ./.env
    ports:
      - "3000:3000"  # comment this if using load-tester only
    depends_on:
      - auth-service
      - data-service
      - websocket-service
      - redis
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "${API_GATEWAY_URL}/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth-service:
    build: ./auth-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "${AUTH_SERVICE_URL}/api/v1/users/health"]
      interval: 10s
      timeout: 5s
      retries: 3


  data-service:
    build: ./data-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "${DATA_SERVICE_URL}/api/v1/data/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  graphql-service:
    build: ./graphql-service
    restart: always
    env_file: ./.env
    depends_on:
      - api-gateway
      - auth-service
      - data-service
      - redis
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "${GRAPHQL_SERVICE_URL}/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker-service:
    build: ./worker-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis
      - mongo

  scheduler-service:
    build: ./scheduler-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis

  websocket-service:
    build: ./websocket-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "${WEBSOCKET_SERVICE_URL}/api/v1/websocket/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  load-tester:
    image: yamaszone/hey
    depends_on:
      - api-gateway
      - auth-service
      - data-service
      - websocket-service
      - worker-service
      - scheduler-service
      - redis
      - mongo

