volumes:
  redis-data:

services:
  redis:
      image: redis:alpine
      restart: always
      ports:
        - "6379:6379" 
      volumes:
        - D:/WEB/redis-data:/data
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  api-gateway:
    build: ./api-gateway
    restart: always
    env_file: ./.env
    ports:
      - "3000:3000"  # comment this if using load-tester only
    depends_on:
      - auth-service
      - data-service
      - websocket-service
      - redis

  auth-service:
    build: ./auth-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis


  data-service:
    build: ./data-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis

  worker-service:
    build: ./worker-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis

  scheduler-service:
    build: ./scheduler-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis

  websocket-service:
    build: ./websocket-service
    restart: always
    env_file: ./.env
    depends_on:
      - redis

  load-tester:
    image: yamaszone/hey
    depends_on:
      - api-gateway
      - auth-service
      - data-service
      - websocket-service
      - worker-service
      - scheduler-service
      - redis

