services:
  api-gateway:
    build: ./api-gateway
    restart: always
    env_file: ./.env
    ports:
      - "3000:3000"  # comment this if using load-tester only
    depends_on:
      - auth-service
      - data-service
      - websocket-service

  auth-service:
    build: ./auth-service
    restart: always
    env_file: ./.env


  data-service:
    build: ./data-service
    restart: always
    env_file: ./.env

  worker-service:
    build: ./worker-service
    restart: always
    env_file: ./.env

  scheduler-service:
    build: ./scheduler-service
    restart: always
    env_file: ./.env

  websocket-service:
    build: ./websocket-service
    restart: always
    env_file: ./.env

  load-tester:
    image: yamaszone/hey
    depends_on:
      - api-gateway
      - auth-service
      - data-service
      - websocket-service
      - worker-service
      - scheduler-service

